trigger:  
    branches:
      include:
        - master

pr: none
    
pool:
    vmImage: 'vs2017-win2016'

stages:
  - stage: Build
    jobs:
    - job: BuildSPFx
      steps:
          - checkout: self

          - task: NodeTool@0
            displayName: 'Use Node 10.x'
            inputs:
                versionSpec: 10.x
                checkLatest: true

          - task: Npm@1
            displayName: 'npm install'
            inputs:
              command: 'install'
              verbose: false   

          - task: Gulp@1
            displayName: 'Gulp Build'
            inputs:
                gulpFile: 'gulpfile.js'
                targets: build 
                
          - task: Gulp@1
            inputs:
              gulpFile: 'gulpfile.js'
              targets: 'bundle'
              gulpjs: 'node_modules/gulp/bin/gulp.js'
              enableCodeCoverage: false
              arguments: '--ship'
              
          - task: Gulp@0
            displayName: 'gulp package-solution'
            inputs:
              gulpFile: 'gulpfile.js'
              targets: 'package-solution'
              arguments: '--ship'
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(build.artifactstagingdirectory)/drop'
            inputs:
                Contents: '**\*.sppkg'
                TargetFolder: '$(build.artifactstagingdirectory)/drop'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'

  - stage: DeployDevelopment
    dependsOn: Build
    jobs:
      - job: DeployDev
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download Build Artifacts
          inputs:
            artifactName: drop
            downloadPath: "$(System.ArtifactsDirectory)"

        - task: PowerShell@2
          displayName: "Publish SPFX App"
          inputs:
            targetType: "inline"
            script: |
              $securePassword = ConvertTo-SecureString $(spPassword) -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential -ArgumentList $(spUsername), $securePassword
              Write-Host 'Connect to sharepoint'
              Connect-PnPOnline -Url https://$(spDomain).sharepoint.com/sites/appcatalog -Credentials $credential
              Write-Host 'Add app to AppCatalog and publish'
              Write-Host 'Artifact Folder:' $(System.ArtifactsDirectory)
              
              Add-PnPApp -Path $(System.ArtifactsDirectory)/drop/react-group-member.sppkg -Overwrite -Publish
              
  - stage: DeployTest
    dependsOn: Build
    jobs:
      - job: DeployTst
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download Build Artifacts
          inputs:
            artifactName: drop
            downloadPath: "$(System.ArtifactsDirectory)"

        - task: PowerShell@2
          displayName: "Publish SPFX App"
          inputs:
            targetType: "inline"
            script: |
              $securePassword = ConvertTo-SecureString $(spPassword) -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential -ArgumentList $(spUsername), $securePassword
              Write-Host 'Connect to sharepoint'
              Connect-PnPOnline -Url https://$(spDomain).sharepoint.com/sites/appcatalog -Credentials $credential
              Write-Host 'Add app to AppCatalog and publish'
              Write-Host 'Artifact Folder:' $(System.ArtifactsDirectory)
              
              Add-PnPApp -Path $(System.ArtifactsDirectory)/drop/react-group-member.sppkg -Overwrite -Publish
